// <auto-generated />
using System;
using AlzaTestProject.DAL.Contextes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlzaTestProject.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("AlzaTestProject.DAL.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-performance laptop for professionals",
                            ImageUrl = "https://example.com/images/product1.jpg",
                            Name = "Laptop Pro 15",
                            Price = 1299.99m,
                            Stock = 25,
                            Updated = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ergonomic wireless mouse",
                            ImageUrl = "https://example.com/images/product2.jpg",
                            Name = "Wireless Mouse",
                            Price = 49.99m,
                            Stock = 100,
                            Updated = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "RGB mechanical keyboard",
                            ImageUrl = "https://example.com/images/product3.jpg",
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            Stock = 50,
                            Updated = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High refresh rate monitor",
                            ImageUrl = "https://example.com/images/product4.jpg",
                            Name = "Gaming Monitor 27\"",
                            Price = 399.99m,
                            Stock = 30,
                            Updated = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Multiport USB-C hub",
                            ImageUrl = "https://example.com/images/product5.jpg",
                            Name = "USB-C Hub",
                            Price = 29.99m,
                            Stock = 75,
                            Updated = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wireless over-ear headphones",
                            ImageUrl = "https://example.com/images/product6.jpg",
                            Name = "Noise-Cancelling Headphones",
                            Price = 199.99m,
                            Stock = 40,
                            Updated = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Latest model with OLED display",
                            ImageUrl = "https://example.com/images/product7.jpg",
                            Name = "Smartphone X",
                            Price = 999.99m,
                            Stock = 60,
                            Updated = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "10-inch tablet with stylus support",
                            ImageUrl = "https://example.com/images/product8.jpg",
                            Name = "Tablet S",
                            Price = 499.99m,
                            Stock = 35,
                            Updated = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fast portable storage",
                            ImageUrl = "https://example.com/images/product9.jpg",
                            Name = "External SSD 1TB",
                            Price = 149.99m,
                            Stock = 80,
                            Updated = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1080p USB webcam",
                            ImageUrl = "https://example.com/images/product10.jpg",
                            Name = "Webcam HD",
                            Price = 69.99m,
                            Stock = 55,
                            Updated = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable wireless speaker",
                            ImageUrl = "https://example.com/images/product11.jpg",
                            Name = "Bluetooth Speaker",
                            Price = 89.99m,
                            Stock = 70,
                            Updated = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fitness smartwatch with heart rate monitor",
                            ImageUrl = "https://example.com/images/product12.jpg",
                            Name = "Smartwatch X",
                            Price = 199.99m,
                            Stock = 40,
                            Updated = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-capacity power bank",
                            ImageUrl = "https://example.com/images/product13.jpg",
                            Name = "Portable Charger 20000mAh",
                            Price = 59.99m,
                            Stock = 90,
                            Updated = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4K waterproof action camera",
                            ImageUrl = "https://example.com/images/product14.jpg",
                            Name = "Action Camera",
                            Price = 249.99m,
                            Stock = 20,
                            Updated = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "True wireless earbuds with charging case",
                            ImageUrl = "https://example.com/images/product15.jpg",
                            Name = "Wireless Earbuds",
                            Price = 129.99m,
                            Stock = 65,
                            Updated = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ergonomic gaming chair with lumbar support",
                            ImageUrl = "https://example.com/images/product16.jpg",
                            Name = "Gaming Chair",
                            Price = 299.99m,
                            Stock = 15,
                            Updated = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Drawing tablet with pen support",
                            ImageUrl = "https://example.com/images/product17.jpg",
                            Name = "Graphics Tablet",
                            Price = 179.99m,
                            Stock = 30,
                            Updated = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wi-Fi controllable LED bulb",
                            ImageUrl = "https://example.com/images/product18.jpg",
                            Name = "Smart Light Bulb",
                            Price = 24.99m,
                            Stock = 120,
                            Updated = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dual-band Wi-Fi router",
                            ImageUrl = "https://example.com/images/product19.jpg",
                            Name = "Router AC1200",
                            Price = 79.99m,
                            Stock = 45,
                            Updated = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wi-Fi smart thermostat for home",
                            ImageUrl = "https://example.com/images/product20.jpg",
                            Name = "Smart Thermostat",
                            Price = 199.99m,
                            Stock = 25,
                            Updated = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rechargeable electric toothbrush",
                            ImageUrl = "https://example.com/images/product21.jpg",
                            Name = "Electric Toothbrush",
                            Price = 59.99m,
                            Stock = 75,
                            Updated = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automatic coffee maker with timer",
                            ImageUrl = "https://example.com/images/product22.jpg",
                            Name = "Coffee Maker",
                            Price = 129.99m,
                            Stock = 40,
                            Updated = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HEPA air purifier for home",
                            ImageUrl = "https://example.com/images/product23.jpg",
                            Name = "Air Purifier",
                            Price = 149.99m,
                            Stock = 30,
                            Updated = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smart robot vacuum cleaner",
                            ImageUrl = "https://example.com/images/product24.jpg",
                            Name = "Robot Vacuum",
                            Price = 299.99m,
                            Stock = 20,
                            Updated = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Waterproof fitness band with heart rate monitor",
                            ImageUrl = "https://example.com/images/product25.jpg",
                            Name = "Fitness Tracker",
                            Price = 99.99m,
                            Stock = 60,
                            Updated = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            Created = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable HD projector for home theater",
                            ImageUrl = "https://example.com/images/product26.jpg",
                            Name = "HD Projector",
                            Price = 399.99m,
                            Stock = 15,
                            Updated = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            Created = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Keyless entry door lock with app control",
                            ImageUrl = "https://example.com/images/product27.jpg",
                            Name = "Smart Door Lock",
                            Price = 199.99m,
                            Stock = 25,
                            Updated = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            Created = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mirrorless camera with 24MP sensor",
                            ImageUrl = "https://example.com/images/product28.jpg",
                            Name = "Digital Camera",
                            Price = 899.99m,
                            Stock = 18,
                            Updated = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            Created = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable external hard drive",
                            ImageUrl = "https://example.com/images/product29.jpg",
                            Name = "External Hard Drive 2TB",
                            Price = 99.99m,
                            Stock = 50,
                            Updated = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            Created = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wi-Fi controlled smart plug",
                            ImageUrl = "https://example.com/images/product30.jpg",
                            Name = "Smart Plug",
                            Price = 19.99m,
                            Stock = 150,
                            Updated = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            Created = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight laptop for everyday use",
                            ImageUrl = "https://example.com/images/product31.jpg",
                            Name = "Laptop Air 13",
                            Price = 999.99m,
                            Stock = 40,
                            Updated = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            Created = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Slim wireless keyboard",
                            ImageUrl = "https://example.com/images/product32.jpg",
                            Name = "Wireless Keyboard",
                            Price = 69.99m,
                            Stock = 60,
                            Updated = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            Created = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-speed HDMI cable",
                            ImageUrl = "https://example.com/images/product33.jpg",
                            Name = "HDMI Cable 2m",
                            Price = 14.99m,
                            Stock = 200,
                            Updated = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            Created = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Protective smartphone case",
                            ImageUrl = "https://example.com/images/product34.jpg",
                            Name = "Smartphone Case",
                            Price = 29.99m,
                            Stock = 120,
                            Updated = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            Created = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adjustable aluminum laptop stand",
                            ImageUrl = "https://example.com/images/product35.jpg",
                            Name = "Laptop Stand",
                            Price = 49.99m,
                            Stock = 55,
                            Updated = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            Created = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-DPI gaming mouse",
                            ImageUrl = "https://example.com/images/product36.jpg",
                            Name = "Gaming Mouse",
                            Price = 59.99m,
                            Stock = 65,
                            Updated = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            Created = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Virtual reality headset for gaming",
                            ImageUrl = "https://example.com/images/product37.jpg",
                            Name = "VR Headset",
                            Price = 399.99m,
                            Stock = 20,
                            Updated = new DateTime(2025, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            Created = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bluetooth smart scale for weight tracking",
                            ImageUrl = "https://example.com/images/product38.jpg",
                            Name = "Smart Scale",
                            Price = 79.99m,
                            Stock = 35,
                            Updated = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            Created = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "14-inch portable USB-C monitor",
                            ImageUrl = "https://example.com/images/product39.jpg",
                            Name = "Portable Monitor",
                            Price = 199.99m,
                            Stock = 25,
                            Updated = new DateTime(2025, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            Created = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wi-Fi security camera with motion detection",
                            ImageUrl = "https://example.com/images/product40.jpg",
                            Name = "Smart Camera",
                            Price = 149.99m,
                            Stock = 30,
                            Updated = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            Created = new DateTime(2025, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "USB-C docking station for laptops",
                            ImageUrl = "https://example.com/images/product41.jpg",
                            Name = "Laptop Docking Station",
                            Price = 179.99m,
                            Stock = 20,
                            Updated = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            Created = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fast wireless charging pad",
                            ImageUrl = "https://example.com/images/product42.jpg",
                            Name = "Wireless Charger",
                            Price = 39.99m,
                            Stock = 80,
                            Updated = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            Created = new DateTime(2025, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wireless Bluetooth headset with mic",
                            ImageUrl = "https://example.com/images/product43.jpg",
                            Name = "Bluetooth Headset",
                            Price = 69.99m,
                            Stock = 55,
                            Updated = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
